# /********************************************************************************
# * Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License, Version 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0.
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# * License for the specific language governing permissions and limitations
# * under the License.
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

# -- The amount of replicas to run
replicaCount: 1

# -- Image of the main container
image:
  # -- Image repository
  repository: tractusx/managed-identity-wallet
  # -- PullPolicy
  pullPolicy: Always
  # -- Image tag (empty one will use "appVersion" value from chart definition)
  tag: ""

# -- Credentials name for private repos
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

# -- Parameters for the application (will be stored in a secret and attached to the container)
secrets:
  # -- Keycloak confidential client id for MIW application
  KEYCLOAK_CLIENT_ID: ""
  # -- AES encryption key used to encrypt/decrypt private keys (random 32 chars - ex.: openssl rand -hex 32)
  ENCRYPTION_KEY: ""

# -- Parameters for the application (will be provided as plain environment variables)
envs:
  # -- Application environments like dev, int, prod
  APPLICATION_ENVIRONMENT: "dev"
  # -- Whether database connection with SSL, true if the database connection is done using SSL
  USE_SSL: "false"
  # -- Initial database connection pool size
  DB_POOL_SIZE: ""
  # -- Keycloak public client id, used only if we want to enable login in swagger using keycloak
  KEYCLOAK_MIW_PUBLIC_CLIENT: ""
  # -- Spring actuator port
  MANAGEMENT_PORT:
  # -- Hostname of miw application
  MIW_HOST_NAME: "localhost"
  # -- Authority/base wallet/root wallet BPN
  AUTHORITY_WALLET_BPN: ""
  # -- Authority/base wallet/root wallet name
  AUTHORITY_WALLET_NAME: ""
  # -- Authority/base wallet/root wallet web did
  AUTHORITY_WALLET_DID: ""
  # -- Verifiable credential schema URL, which will be part of @context in VC
  VC_SCHEMA_LINK: ""
  # -- Default expiry date of issued VC
  VC_EXPIRY_DATE: ""
  # -- Keycloak realm name
  KEYCLOAK_REALM: ""
  # -- Keycloak server url
  AUTH_SERVER_URL: ""

# -- ServiceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# -- Service configuration
service:
  type: ClusterIP
  port: 8080

# -- Ingress configuration
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- PodSecurityContext
podSecurityContext: {}

# -- Preconfigured SecurityContext
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsGroup: 11111
  runAsUser: 11111

# -- Resource boundaries
resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 4
    memory: 1Gi

# -- NodeSelector configuration
nodeSelector:
  "kubernetes.io/os": linux

# -- Tolerations configuration
tolerations: []

# -- Affinity configuration
affinity: {}

# -- PodAnnotation configuration
podAnnotations: {}

# -- Simple Postgresql backup solution (Dump data to second PV)
backup:
  # -- Backup database
  database:
    # -- Enable / Disable the backup
    enabled: false
    # -- Backup schedule (help: https://crontab.guru)
    cron: "* */6 * * *"
    # -- Storage configuration
    storage:
      # -- Set to true, if the PV should stay even when the chart release is uninstalled
      keepStorage: true
      # -- Disk size for backup content
      diskSize: 10G
      # -- storageClassName
      storageClassName: "-"

# -- Configuration of the Postgresql database (internal and external)
postgresql:
  # -- Configure bundled postgresql
  internal:
    # -- Enable bundled database
    enabled: true
  # -- Configure own postgresql database
  external:
    # -- General config
    config:
      # -- Instance host or IP
      host: ""
      # -- Instance port
      port: 5432
      # -- Existing database to use
      database: ""
    auth:
      # -- DB username
      username: ""
      # -- DB password
      password: ""
      # -- Existing secret with provided password
      existingSecret: ""
      # -- Key name of password in secret
      existingSecretKey: password

  # -- Default settings for the primary database and user
  auth:
    # -- username for MIW database
    username: miw
    # -- MIW database name
    database: miw
